travis:
  secure:
    BINSTAR_TOKEN: VJGjAye+OE2ZqD7urvFkSUR4k6SGEMJUQvzuiK6NXkt9MmEc6SbuQbOmiXz3rnQfm8epfLjLy0DovIMEXRsnJ4FpjF+w3nygmEq+usrw+GH7Zfai0NRT4PfcsK2c6JdoK7wC+PtSwiRdBqQ5tZS4OiP/m0mEgtP68fj5RVwueqp+5QevBRivQYdQxsAKIZdzdww9wYNEL5EbctJ0Oc9j4z/7TFtcBpC4H/dLQ+WtgBOCJ+wp5UgeWUn9dnmCbcGrZkq3T3eZVO6dyJl6tfI2hfC/dnh/0sOxysDrVMhztFG+xxi7ohdwwSr3BK0siaMue5GN03yoxHSxRwLPvwv8kP4Z5+JkRRQkubzvw3AyWxW/eeQHJSLT4LeSaiCPTzHqn59A8UXMaAYBQMAfBsuczEX8bYnfxuQEkfVzfjPkbNZRQmLlPDXI9zmKpn0pqlXwQTBmPVnrXcmb97dLI5XxPDjSzmyilKk4m5pmJykjaWsSQgCdJWTSJx/1m7Q/VBZ/l/+0VcEqD8P8F3yQwAGUwTqDkHKblzXRJb9RD9NFBBEjSTiqBUE3pdQ1fqUp2NAoBE4IycwPsbtTTFzzAquuWTHdzwxNAvErWV1Op0dO0j60gLg6UzGvyitdLD4EBNic+V8MX+jrnyhKLtvfTdFcNFq5XCkqTtleoin9UeiI2mQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
