travis:
  secure:
    BINSTAR_TOKEN: D/5B0AULHxP30eD1Q/uN5/5rgB5wDuMgnNFZ5+CsjAvFy3kkXmlfeEYkriBxARnsO/W3HXBGu2DguErc1hEi7heyWrcytixXtb7NfLoHudDXo7959pbRT5iC02gV993gbWrF1Q5GMn9Jb8siCncy9gx6/XrqKBQYbxsgKNZiVTAwK8i98OZnenrRx9Hh4I/+OkF2hbWA2lTyguLn2uk9D/nBeNcQtUWGyFNshJRUDUuPktqpSZfBJwsT3BgcwtTXdzK2NoL457UMh+t/7wkd3tQzqX+ylbSqz+RAwe7Cd3DhM8ofvtY5gtS2OAsyvqWmi4oz/kQaY42WYNfgoHlT/PJS+jrnemw4bvvZkDO4B3vaYeILnN8i3V3XIAfGKOLwb36gCb7COg4xx9DuXej0/ItKRbHHuEOoOmn32+uuX4W1ppxy+5Ws/NnC4DuIlZnWfOjfW/Odzc/ypKv0cWxYKX5iZoG2NFReaU9qu+j6omrvL2FNF39uwrsgxSSLybthMxhJwBRqJRv1K5pbSP19c97XhZhop9Ar/EDVn9H+lX07O1E+FXeHzCfWDL78Z2ne5+dj1Q5MQhOTXhxs59rBy52f+XsNt2EmNkSPPag2RnZmehUYtppLhXpFmqG3l9vWHyO/dJ9oKBc/tGUmNz3pgGrFzF31JBsdxrfHnE6DEPg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
